---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(janitor)
library(ggplot2)
```

```{r}
df1 <- read_csv(here("data_raw", "CU_ACAD_DEPT_WHEN_OFF_ENRL_22740.csv"), skip = 1) %>% clean_names()
df2 <- df1 %>% filter(xor(course_id == 8732, course_id == 8733))
df3 <- df2 %>% filter(component == "LEC")
df4 <- df3 %>% select(course_id, term, term2, tot_enrl, section)
df5 <- df4 %>% distinct()
df6 <- df5 %>% filter(str_detect(term2, "Spring") | str_detect(term2, "Fall")) %>% select(1:5) %>% mutate(ac_year = round((term-4000)/10))
```

```{r}
ma132_spring <- df6 %>% filter(str_detect(term2,"Spring"))
ma132_spring <- ma132_spring %>% group_by(term2, course_id, term, ac_year) %>% summarize(all_enrl = sum(tot_enrl)) %>% filter(course_id == 8733)
ma132_spring %>% ggplot(aes(x=ac_year, y=all_enrl)) + geom_point()
```
```{r}
df_131f = df6 %>% filter(course_id==8732 & str_detect(term2, "Fall")) %>% group_by(ac_year) %>% summarize(ma131_fall=sum(tot_enrl))
df_132s = df6 %>% filter(course_id==8733 & str_detect(term2, "Spring")) %>% group_by(ac_year) %>% summarize(ma132_spring=sum(tot_enrl)) %>% select(2)
df_132fs1 = df6 %>% filter(course_id==8733 & str_detect(term2, "Fall"), section %in% c("1","01A","01B")) %>% group_by(ac_year) %>% summarize(ma132_fall_section_1=sum(tot_enrl)) %>% select(2)
df_132fs23 = df6 %>% filter(course_id==8733 & str_detect(term2, "Fall"), !(section %in% c("1","01A","01B"))) %>% group_by(ac_year) %>% summarize(ma132_fall_other_sections=sum(tot_enrl)) %>% select(2)
df7 = bind_cols(df_131f, df_132fs1, df_132fs23, df_132s, .name_repair = "unique")
df8=df7[1:7,]
```

```{r}
ma131f_132s <- ma131_132 %>% filter(str_detect(term2, "Spring") & course_id == 8733 | str_detect(term2, "Fall") & course_id == 8732 | str_detect(term2, "Fall") & course_id == 8733) %>% mutate(ac_year = round((term-4000)/10))

ma131f_132s <- ma131f_132s %>% select(course_id, term, term2, tot_enrl, section, ac_year) %>% group_by(term2, course_id, term, section, ac_year) %>% summarize(all_enrl = sum(tot_enrl))#, groups %in% c('term2','course_id','term'))


```
```{r echo=FALSE}
linear_regression <- lm(formula=ma132_spring~ma131_fall+ma132_fall_section_1+ma132_fall_other_sections,data=df8)
summary(linear_regression) # multiple regression summary... ma132_spring = 1.1147(ma131_fall) + .2504(ma132_fall_section_1) + .5609(ma132_fall_other_sections) - 219.0157


lm_prediction_ma132s <- data.frame(ac_year = c(22), predicted = c(ceiling(predict(linear_regression, df7[8,])) )) # prediction for MA132 Spring of 2022

df9 <- df8 %>% mutate(predicted = ceiling(predict(linear_regression))) #adding predictions to each year in data set

# plotting the predicted and actual for each year given for MA132 Spring Enrollment
df9 %>% ggplot() +
  geom_point(data = df9, aes(x = ac_year, y = ma132_spring)) +
  geom_point(data = df9, aes(x = ac_year, y = predicted), color = "grey") + ggtitle("MA132 Actual Spring Enrollment vs. Predicted (grey)") + ylab("Number of Students") + xlab("Academic Year") + geom_point(data=lm_prediction_ma132s, aes(x=ac_year, y = predicted), color = "grey")



```

```{r}
```

